version: '3.8'

services:

  mathequizpublic:
    image: tobiaswaggoner/mathequiz:1.0
    ports:
      - "3009:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      # Mount the quizzes directory as an external volume
      - quiz-data:/app/public/quizzes
volumes:
  quiz-data:
    driver: local